---
title: "Plots for simulation scenarios"
author: "Mo Yin"
date: "2023-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# clean environment 
rm(list = ls())

# set working directory to the `practical/` folder 
wd = '~/Documents/GitHub/practical/'
setwd(wd)

# load libraries and functions
scripts = paste0(wd, 'Code/Functions/', list.files('Code/Functions/'))
lapply(scripts, source)

# load data in the output folder 
files = list.files(path = paste0(wd, 'Code/Run_output'), full.names = TRUE, pattern = "*.rds")
outputs = list()
for (file in files){
  outputs[[sub('.*/', '', file)]] = readRDS(file)
}

# define colors and shapes 
method_labs = c("Fixed-effect (frequentist)", "Fixed-effect (Bayesian, non-informative prior)",
                "Fixed-effect (Bayesian, weakly-informative prior)", "Fixed-effect (Bayesian, strongly-informative prior)", 
                "Mixed-effect (frequentist)", "Mixed-effect (Bayesian, non-informative prior)", 
                "Fixed-effect (Bayesian, weakly-informative prior)", "Fixed-effect (Bayesian, strongly-informative prior)")
shapes = c(0, 1, 2, 5, 15, 16, 17, 18)
colors = c("#1f78b4",  "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#a6cee3", "#b2df8a", "#fb9a99")
names(shapes) = names(colors) = method_labs
```

## Final analysis report {.tabset .tabset-fade .tabset-pills}

### Power

```{r, echo = FALSE, fig.align="center",fig.height = 6, fig.width = 12}



```


### Type 1 error

```{r, echo = FALSE, fig.align="center",fig.height = 6, fig.width = 12}

```
